# Generated by Django 2.0.4 on 2018-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_acctive',
            field=models.BooleanField(default=False),
        ),
    ]
