# Generated by Django 2.0.4 on 2018-06-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_is_acctive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='is_acctive',
            new_name='is_active',
        ),
    ]
